# Hiring Agent

# The solution will be highly scalable so that it can used in quickest way possible.

# Steps followed:(Till now work in progress)

1. The organization just needs to create a google form and share it with the candidates.

<Google Form Example>(https://docs.google.com/forms/d/e/1FAIpQLSd57uT3Rx4owzFn1rImQGoVBpy94zYXVuFhq0f3s9Ly_YrXcw/viewform)

Note - This form is important since every organization has their own hiring process and criteria.We want to help you screen the candidates based on your criteria in the quickest way possible.